### ISSUE TITLE
Escape " in Annotation

### ISSUE THREAD

**Issue by Baachi** [doctrine/common#141]
Is it possible to protect a quotation mark, for example, with a "\"?

Like this:

``` php
<?php
/**
 * @Unique(fields={"name"}, message="The name \"{{ value }}\" is already in use!")
 */
class User {}
```

**Comment by wraycode** [comment]
how do I get rid on the backslashes the double " adds to my example?

**Comment by xiaozixiangfeng** [comment]
I want to know if I can get ideas in these two areas:
1: Is it possible to do this by overriding the AnnotationReader class, but I'm not sure what his specific implementation idea is, and there are many details to be aware of.
2: php syntax support, such as string type can be achieved using a delimiter such as <<< EOF.

**Comment by Majkl578** [comment]
Ad 1: For the upcoming Annotations 2.0 it's planned to switch to `\` as an escape character. This can't to be done in 1.x.
Ad 2: If you have some proposals, I'd suggest to open an issue over on [doctrine/annotations](https://github.com/doctrine/annotations) repo instead of discussing it here in a old, closed issue.
