### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/.../app/cache/prod/doctrine/orm/Proxies/__CG__OpensoftOnpBundleWebBundleEntityvar.php'

### ISSUE THREAD

**Issue by molchanoviv** [doctrine/common#305]
Hello guys.

Hello guys. We have Symfony2 application which uses Doctrine and Doctrine Bundle. After update to 1.2.*@dev i got an error

```
PHP Fatal error:  require(): Failed opening required '/.../app/cache/prod/doctrine/orm/Proxies/__CG__OpensoftOnpBundleWebBundleEntityvar.php'
```

I figured out that doctrine tries to read annotations from proxy classes. Then checks whether classes of found annotations is exists or not. It runs DocPaser->classExists(). this function runs class_exists() And on this step i got an error. Because Autoloader::register() requires this nonexistent file. Maybe i'd be better to add file_exists before requiring it? I asked this question [here](https://github.com/doctrine/DoctrineBundle/issues/230) but no one answered. :(

Also Why doctrine reads annotations from proxy classes which generated by doctrine itself?

**Comment by ostrolucky** [comment]
I have analyzed this issue. This can happen only if something called `Doctrine\Common\Annotations\AnnotationRegistry::registerLoader` with [invalid loader](https://github.com/doctrine/annotations/blob/54cacc9b81758b14e3ce750f205a393d52339e97/lib/Doctrine/Common/Annotations/AnnotationRegistry.php#L99), which is in this case `Doctrine\Common\Proxy\Autoloader::register`.

As this is generally done in user space, this cannot be considered as a doctrine bug, but user error or error in foreign code. Therefore this issue is safe to close @stof @Ocramius

**Comment by Ocramius** [comment]
Thanks @ostrolucky!
