### ISSUE TITLE
v3.4.0 ProxyGenerator Warning: Undefined array key

### ISSUE THREAD

**Issue by forgie1** [doctrine/common#982]
doctrine/common version: `3.4.0`
PHP version:  `8.1.1`

This code
```
$qb = $this->getEntityManager()->createQueryBuilder();
$qb->from(EntityName::class), 'n', null);
$qb->select('n, nd');
$qb->join('n.someJoinName', 'nd')
	->where('nd.language = :lang')->setParameter('lang', $lang)
	->andWhere('nd.nid = :nid')->setParameter('nid', $nid);
$qb->getQuery()->getOneOrNullResult();
```

Results to following warning in `\vendor\doctrine\common\src\Proxy\ProxyGenerator.php:1131`:

```
Warning
Undefined array key 1
```

This didn't happen in version `3.3.1`

**Comment by malarzm** [comment]
@forgie1 line 1131 sounds weird as that's just phpdoc https://github.com/doctrine/common/blob/d534f19a915823f41561ed9a2231a912f8b6e241/src/Proxy/ProxyGenerator.php#L1131

I guess the problem lies somehow in line 1125 https://github.com/doctrine/common/blob/d534f19a915823f41561ed9a2231a912f8b6e241/src/Proxy/ProxyGenerator.php#L1125 as that's the new code version 3.4.0 introduced. Sadly the code you've pasted tells me nothing about the root cause, one of your entity's methods must have a default value for parameter we fail to support correctly. Could you please check which one is it? Also a PR with a failing test case would help us a lot. For reference how to write such tests you can take a look here: https://github.com/doctrine/common/pull/966

**Comment by malarzm** [comment]
Oops, I've checked current branch writing above, indeed the line is correct in tagged version: https://github.com/doctrine/common/blob/3.4.0/src/Proxy/ProxyGenerator.php#L1131. Still, we'd greatly appreciate a reproducer

**Comment by forgie1** [comment]
@malarzm it looks like it fails on this parameter:
```
	/**
	 * @var Url|null
	 * @ORM\ManyToOne(targetEntity="Url")
	 * @ORM\JoinColumn(nullable=true, onDelete="RESTRICT")
	 */
	private $alias;
```

Setter for our parameter named `alias` has `null` default value:

```
	/**
	 * @param null|Url $alias
	 * @return $this
	 */
	public function setAlias(Url $alias = null)
	{
            ...
```

$parameter passed to `ProxyGenerator::getParameterDefaultValue(ReflectionParameter $parameter)` is:
```
Nette\Reflection\Parameter
    function: 
        array
            0 => 'Plugins\Urls\Models\Url'
            1 => 'setAlias'
    name: 'alias'
```

Result of `explode('$' . $parameter->getName() . ' = ', (string) $parameter, 2)` is
```
array
    0 => '$alias in Plugins\Urls\Models\Url::setAlias()'
```

So there is really no array key 1.

To prepare failing test I would have to delve more into the Doctrine Common.

**Comment by malarzm** [comment]
This seems weird, reflection's string representation is correct: https://3v4l.org/qGBdg#v8.1.9.

The thing that stands out to me, why do you have an instance of `Nette\Reflection\Parameter` passed instead of native reflection?

**Comment by malarzm** [comment]
Having Nette's reflection is exactly the culprit as it has its own `__toString` method: https://github.com/nette/reflection/blob/master/src/Reflection/Parameter.php#L86-L89

**Comment by malarzm** [comment]
To elaborate a bit: `\ReflectionParameter::__toString` is used so we can support https://wiki.php.net/rfc/new_in_initializers and there's really no other way to do that. Given https://github.com/nette/reflection is discontinued and last release was in 2017 I'm inclined to say we will not provide extra support for it.

**Comment by forgie1** [comment]
@malarzm you are right, this was the problem
Thank you for your support.
